### PR TITLE
Issue #27 document the api

### PR DESCRIPTION
**Pull request by BrainIsDead**
Added sphinx auto doc

### CODE REVIEW

**Comment by minhkhul** [comment]
close #27

**Comment by melange396** [comment]
wow, theres a lot in here!  do you have a version of this being served somewhere (so we can browse the pages)?

do you want to add the generation step to a pre-commit hook or something like that?

**Comment by minhkhul** [comment]
> wow, theres a lot in here!  do you have a version of this being served somewhere (so we can browse the pages)?

The serving on staging comes after this is merged into development. For now we can see the pages locally by building the containers then go to /docs.

**Comment by BrainIsDead** [comment]
> wow, theres a lot in here! do you have a version of this being served somewhere (so we can browse the pages)?
> 
> do you want to add the generation step to a pre-commit hook or something like that?

Good idea! Thanks

**Review by minhkhul — APPROVED** [review]

**Pull request merged**
